### ISSUE TITLE
Is this still functional ?

### ISSUE THREAD

**Issue by mocallins** [v1tal3/netconfig#90]
I didn't have an old version of Ubuntu, so i tried with the latest: Ubuntu 22.04.0(3)?

followed all the steps and it had a failure at creating the db

```
netconfig@netopeer:~/netconfig$ python db_create.py
Traceback (most recent call last):
  File "/home/netconfig/netconfig/db_create.py", line 7, in <module>
    from app import db
  File "/home/netconfig/netconfig/app/__init__.py", line 2, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.10/dist-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.10/dist-packages/jinja2/__init__.py)
```

**Comment by routetehpacketz** [comment]
It appears Flask deprecated importing Markup in v2.3.0: https://flask.palletsprojects.com/en/3.0.x/changes/#version-2-3-0

Were you able to run `pip install -r requirements.txt` without error?

**Comment by mocallins** [comment]
I don't think it is running without error:WARNING: Error parsing dependencies of celery: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    pytz (>dev)
         ~^

    On Sunday, June 30, 2024 at 09:51:17 AM CDT, routetehpacketz ***@***.***> wrote:  
 
 


It appears Flask deprecated importing Markup in v2.3.0: https://flask.palletsprojects.com/en/3.0.x/changes/#version-2-3-0

Were you able to run pip install -r requirements.txt without error?

**Comment by mocallins** [comment]
> I don't think it is running without error:WARNING: Error parsing dependencies of celery: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier     pytz (>dev)          ~^ On Sunday, June 30, 2024 at 09:51:17 AM CDT, routetehpacketz ***@***.***> wrote: It appears Flask deprecated importing Markup in v2.3.0: https://flask.palletsprojects.com/en/3.0.x/changes/#version-2-3-0 Were you able to run pip install -r requirements.txt without error? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

So what does this mean that i need to do ?

**Comment by mocallins** [comment]
Okay so figured out the markupsafe, but now we get this error:

```
netconfig@netopeer:~/netconfig$ python db_create.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/helpers.py", line 24, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.10/dist-packages/werkzeug/urls.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/netconfig/netconfig/db_create.py", line 7, in <module>
    from app import db
  File "/home/netconfig/netconfig/app/__init__.py", line 2, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.10/dist-packages/flask/__init__.py", line 24, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 23, in <module>
    from .helpers import _PackageBoundObject, url_for, get_flashed_messages, \
  File "/usr/local/lib/python3.10/dist-packages/flask/helpers.py", line 26, in <module>
    from urlparse import quote as url_quote
ModuleNotFoundError: No module named 'urlparse'
netconfig@netopeer:~/netconfig$


```

**Comment by ghost** [comment]
>ModuleNotFoundError: No module named 'urlparse'

I read over the README and install docs to see if it specifically stated which Python version this was built and tested with, but could not see where it indicates. This message now appears to be a result of this project being developed in Python 2. The `urlparse` module was seemingly incorporated into `urllib` in Python 3. 

`from urllib.parse import quote as url_quote` appears to work, so you _may_ be able to find/replace `urlparse` with `urllib.parse` within the project's files and try the install again.

**Comment by mocallins** [comment]
Yea just doing some simple finds and grep for that string  "urlparse" get pretty hairy and all the files it appeared in, i think i'd probably just break it worse.

If that's the best answer we have, then i'd just say this doesn't work any longer.
But would be happy and try again, if you guys want to fix it all.

Thanks
